-- Menu seed is managed by MenuRouteDefinitions.cs (synced on API startup via MenuRouteSync).
-- Canonical routes match resta-app/src/app/app.routes.ts authenticated child routes.
-- Do not edit this file manually; update MenuRouteDefinitions.cs instead.

SET NOCOUNT ON;
